# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 510, 231, 31))
        self.pushButton.setObjectName("pushButton")
        self.line_link = QtWidgets.QLineEdit(self.centralwidget)
        self.line_link.setGeometry(QtCore.QRect(10, 190, 681, 21))
        self.line_link.setText("")
        self.line_link.setObjectName("line_link")
        self.line_num = QtWidgets.QLineEdit(self.centralwidget)
        self.line_num.setGeometry(QtCore.QRect(10, 260, 201, 20))
        self.line_num.setText("")
        self.line_num.setObjectName("line_num")
        self.label_num = QtWidgets.QLabel(self.centralwidget)
        self.label_num.setGeometry(QtCore.QRect(10, 240, 171, 16))
        self.label_num.setObjectName("label_num")
        self.label_link = QtWidgets.QLabel(self.centralwidget)
        self.label_link.setGeometry(QtCore.QRect(10, 170, 161, 16))
        self.label_link.setObjectName("label_link")
        self.line_start = QtWidgets.QLineEdit(self.centralwidget)
        self.line_start.setGeometry(QtCore.QRect(10, 330, 201, 20))
        self.line_start.setObjectName("line_start")
        self.label_start = QtWidgets.QLabel(self.centralwidget)
        self.label_start.setGeometry(QtCore.QRect(10, 310, 161, 16))
        self.label_start.setObjectName("label_start")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 400, 201, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_stop = QtWidgets.QLabel(self.centralwidget)
        self.label_stop.setGeometry(QtCore.QRect(10, 380, 161, 16))
        self.label_stop.setObjectName("label_stop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoRia Parser"))
        self.pushButton.setText(_translate("MainWindow", "Старт"))
        self.label_num.setText(_translate("MainWindow", "Введите количество страниц:"))
        self.label_link.setText(_translate("MainWindow", "Введите ссылку:"))
        self.label_start.setText(_translate("MainWindow", "С какой страницы начать:"))
        self.label_stop.setText(_translate("MainWindow", "Сколько номеров записать:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
